export const language_options = [
    { label: "English", value: "EN-GB" }, 
    { label: "Dutch", value: "NL" }, 
    { label: "Bulgarian", value: "BG" }, 
    { label: "Czech", value: "CS" }, 
    { label: "Danish", value: "DA" }, 
    { label: "German", value: "DE" }, 
    { label: "Greek", value: "EL" }, 
    { label: "Spanish", value: "ES" }, 
    { label: "Estonian", value: "ET" }, 
    { label: "Finnish", value: "FI" },
    { label: "French", value: "FR" }, 
    { label: "Hungarian", value: "HU" }, 
    { label: "Indonesian", value: "ID" }, 
    { label: "Italian", value: "IT" }, 
    { label: "Japanese", value: "JA" }, 
    { label: "Lithuanian", value: "LT" }, 
    { label: "Latvian", value: "LV" }, 
    { label: "Polish", value: "PL" }, 
    { label: "Portuguese (Brazilian)", value: "PT-BR" }, 
    { label: "Portuguese (European)", value: "PT-PT" }, 
    { label: "Romanian", value: "RO" }, 
    { label: "Russian", value: "RU" }, 
    { label: "Slovak", value: "SK" }, 
    { label: "Slovenian", value: "SL" }, 
    { label: "Swedish", value: "SV" }, 
    { label: "Turkish", value: "TR" }, 
    { label: "Ukrainian", value: "UK" }, 
    { label: "Chinese (simplified)", value: "ZH" }
];

